#include <string>

#define 🚗 auto
#define ✔️ true
#define ❌ false
#define 💔 break
#define 💼 case
#define 📕 case
#define 🎣 catch
#define 🅰️ char
#define 📙 std
#define 🔤 📙::string
#define ➕ +
#define ➖ -
#define ➡️ ->
#define 👩‍🏫 class
#define 🧱 const
#define 🔜 continue
#define 🤓 default
#define 🚫 delete
#define 👯 double
#define 🤔 if
#define 🤷 else
#define 🔞 explicit
#define 📁 export
#define 📤 extern
#define ☁️ float
#define 🤝 friend
#define 🔀 for
#define 🚀 inline
#define ✊ do
#define 🔟 int
#define 🥒 long
#define 🥕 short
#define 🧠 void
#define 🌐 namespace
#define 🆕 new
#define 💳 nullptr
#define 👨‍ operator
#define 🍆 private
#define 👮 protected
#define 🍑 public
#define ®️ register
#define 🎭 reinterpret_cast
#define 📝 requires
#define 🔙 return
#define ♾️ signed
#define 📏 sizeof
#define ⚡ static
#define 🏠 struct
#define 🧮 switch
#define 🛕 template
#define 👀 this
#define 🤾 throw
#define 🤞 try
#define 🧅 union
#define 😊 unsigned
#define 👩 using
#define 💑 virtual
#define 🤡 bool
#define 🔄 while
#define 👉 *
#define 🤝 ==
#define ︵ (
#define ︶ )
#define 🛑 ;
#define ︷ {
#define ︸ }
#define 💾 =
